# Generated by Django 4.2.7 on 2023-11-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_for_sale',
            field=models.BooleanField(default=True),
        ),
    ]
